#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"

# 自定义脚本检查
node "$(dirname -- "$0")/pre-check.cjs"

# 如果检查通过，根据 package.json 的 lint-staged，对提交的文件 lint 检查并修复
pnpm exec lint-staged
